//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeQueueServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_freeQueueEntities : DbContext
    {
        public DB_freeQueueEntities()
            : base("name=DB_freeQueueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_menuAddittions> tbl_menuAddittions { get; set; }
        public virtual DbSet<tbl_menuTastes> tbl_menuTastes { get; set; }
        public virtual DbSet<tbl_productsCategories> tbl_productsCategories { get; set; }
        public virtual DbSet<tbl_purchases> tbl_purchases { get; set; }
        public virtual DbSet<tbl_purchasesAdditions> tbl_purchasesAdditions { get; set; }
        public virtual DbSet<tbl_purchasesProducts> tbl_purchasesProducts { get; set; }
        public virtual DbSet<tbl_purchasesTastes> tbl_purchasesTastes { get; set; }
        public virtual DbSet<tbl_stores> tbl_stores { get; set; }
        public virtual DbSet<tbl_storesActivityTime> tbl_storesActivityTime { get; set; }
        public virtual DbSet<tbl_storesMenu> tbl_storesMenu { get; set; }
    }
}
