//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeQueueServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_menuAddittions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_menuAddittions()
        {
            this.tbl_purchasesAdditions = new HashSet<tbl_purchasesAdditions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Product { get; set; }
        public string Addition { get; set; }
        public Nullable<double> AddtionPrice { get; set; }
        public Nullable<bool> AdditionStatus { get; set; }
        public string AdditionImage { get; set; }
    
        public virtual tbl_storesMenu tbl_storesMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_purchasesAdditions> tbl_purchasesAdditions { get; set; }
    }
}
