//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeQueueServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchasesTastes
    {
        public int Id { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Taste { get; set; }
    
        public virtual tbl_menuTastes tbl_menuTastes { get; set; }
        public virtual tbl_purchasesProducts tbl_purchasesProducts { get; set; }
    }
}
