//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeQueueServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_storesActivityTime
    {
        public int Id { get; set; }
        public Nullable<int> Store { get; set; }
        public Nullable<int> ActivityDay { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
    
        public virtual tbl_stores tbl_stores { get; set; }
    }
}
