//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeQueueServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_storesMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_storesMenu()
        {
            this.tbl_menuAddittions = new HashSet<tbl_menuAddittions>();
            this.tbl_menuTastes = new HashSet<tbl_menuTastes>();
            this.tbl_purchasesProducts = new HashSet<tbl_purchasesProducts>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Store { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public Nullable<double> ProductPrice { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
        public Nullable<bool> QuickProduct { get; set; }
        public string ProductImage { get; set; }
        public Nullable<int> PreperationTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_menuAddittions> tbl_menuAddittions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_menuTastes> tbl_menuTastes { get; set; }
        public virtual tbl_productsCategories tbl_productsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_purchasesProducts> tbl_purchasesProducts { get; set; }
        public virtual tbl_stores tbl_stores { get; set; }
    }
}
