//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeQueueServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_purchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_purchases()
        {
            this.tbl_purchasesProducts = new HashSet<tbl_purchasesProducts>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public string CreditCard { get; set; }
        public string CreditDate { get; set; }
        public string CreditDigits { get; set; }
        public string DeliveryAddress { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ReservedSeats { get; set; }
        public Nullable<bool> Club { get; set; }
        public Nullable<double> Tip { get; set; }
        public Nullable<double> PurchaseSum { get; set; }
        public string ReceiptTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_purchasesProducts> tbl_purchasesProducts { get; set; }
        public virtual tbl_stores tbl_stores { get; set; }
    }
}
